In [23]:
'''Write a Python program that declares variables of different data types (e.g., string, integer, float,
and boolean). Output the variables in a sentence format using print() and f-strings.'''
name = "supriya"
num=12
c = 3.14
b = True
print(f"string:{name}")
print(f"integer:{num}")
print(f"float:{c}")
print(f"boolean value:{b}")



string:supriya
integer:12
float:3.14
boolean value:True


In [42]:
'''Write a Python program that takes an integer input and checks whether the number is positive,
negative, or zero using conditional statements (if-else).'''
num=int(input("enter a number:"))
if(num>0):
    print("positive number")
elif(num<0):
    print("negative number")
else:
    print("number is zero")

enter a number: 0


number is zero


In [1]:
'''Write a Python program that takes a number as input and prints the multiplication table
for that number (from 1 to 10).'''
num=int(input("enter a number:"))
for i in range(1,11):
    print(i, "*", num ,"=" ,i*num)

enter a number: 3


1 * 3 = 3
2 * 3 = 6
3 * 3 = 9
4 * 3 = 12
5 * 3 = 15
6 * 3 = 18
7 * 3 = 21
8 * 3 = 24
9 * 3 = 27
10 * 3 = 30


In [62]:
''' Create a Python list that contains the names of 5 different fruits. Perform the given operations on
the list.'''
fruits = ['apple', 'banana', 'cherry', 'orange', 'grape']
fruits.append("kiwi")
fruits.remove("banana")
fruits.sort()
fruits.append("fruits")
print(fruits)


['apple', 'cherry', 'grape', 'kiwi', 'orange', 'fruits']


In [77]:
''' Write a Python program that creates a tuple containing 5 numbers. Perform the given operations
on the tuple.'''
n = (1, 2, 3, 4, 5)
print(n[0])
print(n[-2])
print(n[0:2])
print(len(n))
n1=(6,7,8,9,9)
print(n+n1)


1
4
(1, 2)
5
(1, 2, 3, 4, 5, 6, 7, 8, 9, 9)


In [95]:
'''Create a dictionary that stores the names of 3 students as keys and their marks in mathematics as
values. Perform the given operations.'''
s= {'sita': 90, 'ram': 80, 'shurthi': 85,}
print(s["sita"])
print(s["ram"])
s.keys()
s.values()
del s["sita"]
print(s)

90
80
{'ram': 80, 'shurthi': 85}


In [107]:
'''Create two sets of integers. Perform the given set operations.'''
s1 = {1, 2, 3, 4}
s2 = {3, 4, 5, 6}
print(s1.union(s2))
print(s1.intersection(s2))
s1.add(10)
print(s1)
s2.add(11)
print(s2)

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2, 3, 4, 10}
{3, 4, 5, 6, 11}


In [109]:
'''Write a Python function called find_largest() that takes a list of numbers as input and returns the
largest number from the list. Test the function with a sample list'''
def find_largest(num):
    return max(num)
n=[1,2,5,6,7,9,8]
print(find_largest(n))

9


In [115]:
'''Use list comprehension to create a list of squares of all even numbers between 1 and 20.'''
l=[x**2 for x in range(1,21)  if x%2==0]
print(l)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [120]:

''' Write a Python script that uses a lambda function to calculate the product of two numbers provided
by the user.'''
p = lambda a, b: a * b
n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))
print(f"Product: {p(n1, n2)}")

Enter first number:  2
Enter second number:  3


Product: 6


In [132]:
'''Write a Python program to create a one-dimensional, two-dimensional, and three-dimensional
NumPy array. Print the shape and dimensions of each array'''
import numpy as np


arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
arr2 = np.array([[1, 2,3,4], [3, 4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
arr3 = np.array([[[1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)


[1 2 3 4]
1
(4,)
[[1 2 3 4]
 [3 4 5 6]]
2
(2, 4)
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
3
(2, 2, 4)


In [160]:
'''Write a Python program to create a 5x5 NumPy array of random integers and Perform array
indexing as given'''
import numpy as np

b=np.arange(1,26).reshape(5,5)

print(b)
print(b[0])

print(b[0:2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [162]:
'''create a NumPy array of shape (4, 4) containing numbers from 1 to 16. Use slicing to extract for
the given conditions'''
import numpy as np
a=np.arange(1,17).reshape(4,4)
print(a)
print(a[2])
print(a[0:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


In [166]:
''' create a NumPy array of shape (4, 4) containing numbers from 1 to 16. Use slicing to extract for
the given condition'''
import numpy as np
a=np.arange(1,17).reshape(4,4).flatten()
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [171]:
'''Write a Python program that creates a 2D array of shape (6, 2) using np.arange() and then reshapes
it into a 3D array of shape (2, 3, 2). Flatten the reshaped array and print the result'''
arr = np.arange(12).reshape(6, 2)
reshaped = arr.reshape(2, 3, 2)
a = reshaped.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(A + B)   
print(A - B)  
print(A * B)  
print(A / B)  

In [173]:
#Write a Python program to demonstrate broadcasting. Create an array of shape (3, 3) and add a one-
#dimensional array of shape (1, 3) to it using broadcasting
a=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[6,7,8]],[[1,2,6],[5,6,7]]])
a1=np.array([1,2,3])
print(a+a1)

[[[ 2  4  6]
  [ 5  7  9]]

 [[ 7  9 11]
  [ 7  9 11]]

 [[ 2  4  9]
  [ 6  8 10]]]


In [181]:
'''Create two NumPy arrays of the same shape, A and B. Perform the following arithmetic operations:
Element-wise addition.
Element-wise subtraction.
Element-wise multiplication.
Element-wise division.'''
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(b-a)
print(a*b)
print(a/b)
print(b/a)

[ 6  8 10 12]
[-4 -4 -4 -4]
[4 4 4 4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[5.         3.         2.33333333 2.        ]


In [3]:

'''Create a Pandas DataFrame with the given Name and marks of 3 courses:
Add a new column named 'Total' that represents the sum of all the courses. Add 'Grade' based
on the values of the 'Total'. Print the updated DataFrame with the new 'Total' and 'Grade'
column.'''
import pandas as pd


data = {'Name': ['sita', 'siya', 'Cat'], 'Math': [80, 70, 90], 'Science': [85, 75, 95], 'English': [88, 78, 92]}
df = pd.DataFrame(data)

df['Total'] = df['Math'] + df['Science'] + df['English']
df['Grade'] = df['Total'].apply(lambda x: 'A' if x >= 250 else 'B')

print(df)


   Name  Math  Science  English  Total Grade
0  sita    80       85       88    253     A
1  siya    70       75       78    223     B
2   Cat    90       95       92    277     A


In [3]:
'''Calculate and interpret mean, median, mode, variance and standard deviation for a given dataset.
Data =[ 15,21,29,21,15,24,32,21,15,30]'''
import pandas as pd
data = [15, 21, 29, 21, 15, 24, 32, 21, 15, 30]
data_series = pd.Series(data)
mean_value = data_series.mean()
print("Mean:", mean_value)
median_value = data_series.median()
print("Median:", median_value)
mode_value = data_series.mode()[0]  
print("Mode:", mode_value)
variance_value = data_series.var()
print("Variance:", variance_value)
std_deviation_value = data_series.std()
print("Standard Deviation:", std_deviation_value)


Mean: 22.3
Median: 21.0
Mode: 15
Variance: 40.67777777777778
Standard Deviation: 6.3779132776934


In [18]:
import pandas as pd
df = pd.read_csv('robot.csv')
print(df.head())
summary_stats = df.describe()
print("Summary Statistics:")
print(summary_stats)
correlation_matrix = df.corr()
print("Correlation Matrix:")
print(correlation_matrix)
z_scores = (df[['Interaction_Count', 'Steps_Walked', 'Objects_Recognized', 'Learning_Sessions', 'Energy_Consumption (kWh)']] - df.mean()) / df.std()
print("Z-Scores for detecting outliers:")
print(z_scores)


  Robot_ID   Task_Type Component_ID Sensor_Type            Sensor_Data  \
0  RBT_001  Inspection      CMP_460       LIDAR  1 (obstacle detected)   
1  RBT_002    Assembly      CMP_252     Thermal             85.3 (°C)   
2  RBT_003  Inspection      CMP_248     Thermal       92% (visual fit)   
3  RBT_004     Welding      CMP_433      Camera      98% (defect-free)   
4  RBT_005    Assembly      CMP_992      Camera       92% (visual fit)   

   Processing_Time (s)  Accuracy (%) Environmental_Status  \
0                 67.0          90.4               Stable   
1                 71.2          98.1               Stable   
2                 49.2          95.3             Unstable   
3                 74.5          90.2               Stable   
4                 64.5          97.2             Unstable   

   Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
0                       2.2                        No               Yes   
1                       2.7           

ValueError: could not convert string to float: 'RBT_001'

In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("robot.csv")
df.head()

In [ ]:
average = df.Interaction_Count.mean()